### ISSUE TITLE
multiple java destinations java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng-incubator#111]
It is apparently not possible to use multiple java destinations using the same class:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Native Library /usr/lib64/syslog-ng/libmod-java.so already loaded in another classloader
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1895)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1119)
        at org.syslog_ng.SyslogNg.<clinit>(SyslogNg.java:28)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:344)
        at org.syslog_ng.SyslogNgClassLoader.loadClass(SyslogNgClassLoader.java:57)
```

**Comment by juhaszviktor** [comment]
Thanks, I was also faced with this problem. I have solution, but it is under review/testing phase.

**Comment by juhaszviktor** [comment]
#113 fixes this bug
